// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obvjcjpwgyureangvqsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9idmpjanB3Z3l1cmVhbmd2cXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjI5NTgsImV4cCI6MjA2OTY5ODk1OH0.CFHv_Aru4iW_MPzTytEgWKRuf0MYLNdFTcXdasz67mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});